import days from './data/days.json';
import encounters from './data/encounters.p1.json';
import phrases from './data/phrases.json';
import exams from './data/exam.json';
import {createInitialState} from './engine/state.js';
import {loadFromStorage,saveToStorage,importSave,exportSave} from './engine/save.js';
import {gradeAnswer} from './engine/grading.js';
import {reviewWord} from './engine/vocab.js';
import {dialogue} from './ui/components/dialogue.js';
import {statusBar} from './ui/components/statusBar.js';
import {fillBlank} from './ui/components/fillBlank.js';
import {speakMalay,hasMalayVoice} from './ui/tts.js';

const root=document.querySelector('#app');let state=loadFromStorage()||createInitialState();let screen='title';let currentExam=[];let q=0,score=0;
function persist(){try{saveToStorage(state)}catch{}}
function button(parent,label,fn,secondary=false){const b=document.createElement('button');b.textContent=label;if(secondary)b.className='secondary';b.addEventListener('click',fn);parent.append(b);return b}
function go(next){screen=next;render()}
function render(){root.replaceChildren();const wrap=document.createElement('section');root.append(wrap);statusBar(wrap,state);const title=document.createElement('h1');title.textContent='Kawan Melayu｜便利商店馬來語';wrap.append(title);
if(screen==='title'){title.textContent='歡迎來到 Kawan Melayu';wrap.append(document.createTextNode('離線也能玩的馬來語便利商店旅程'));button(wrap,'開始／繼續冒險',()=>go('briefing'));button(wrap,'單字本',()=>go('vocabBook'));button(wrap,'設定與存檔',()=>go('settings'));return}
if(screen==='briefing'||screen==='store'||screen==='summary'){if(state.day>10){go('exam');return}const d=days.find(x=>x.day===state.day);const enc=encounters.find(x=>x.id===d?.encounterId);const cast={abang_zul:'Abang Zul',kak_siti:'Kak Siti',amir:'Amir',pak_cik_hamid:'Pak Cik Hamid'};dialogue(wrap,cast[enc?.speaker]||'Abang Zul',`${d?.title||`第 ${state.day} 天`}：${d?.story||'歡迎光臨！'} ${enc?.lines?.[0]?.ms||''} ${enc?.lines?.[0]?.zh||''}`,{typewriter:true,onSpeak:hasMalayVoice()?()=>speakMalay(enc?.lines?.[0]?.ms||'Selamat datang!'):undefined});const input=fillBlank(wrap,'輸入馬來語回應（輸入 1-4 可選）');button(wrap,'提交回應',()=>{const answer=input.value.trim();const correct=answer.length>0;const vocabId=enc?.vocab?.[0];if(vocabId)state=reviewWord(state,vocabId,correct);state.experience+=(correct?10:2);state.level=Math.min(3,1+Math.floor(state.experience/40));state.history.push({day:state.day,answer,correct});state.cash+=correct?2:0;state.day++;persist();if(state.day>10)go('exam');else go('summary')});button(wrap,'借款／救濟（Pak Cik Hamid）',()=>{state.cash+=10;state.history.push({day:state.day,relief:true});persist();render()},true);button(wrap,'單字本',()=>go('vocabBook'),true);button(wrap,'回主選單',()=>go('title'),true);return}
if(screen==='vocabBook'){title.textContent='單字本｜依分類';const categories=[...new Set(phrases.map(x=>x.category||'日常'))];const select=document.createElement('select');const all=document.createElement('option');all.textContent='全部分類';all.value='';select.append(all);categories.forEach(c=>{const o=document.createElement('option');o.textContent=c;o.value=c;select.append(o)});wrap.append(select);const list=document.createElement('div');wrap.append(list);const update=()=>{list.replaceChildren();phrases.filter(p=>!select.value||p.category===select.value).forEach(p=>{const row=document.createElement('div');row.className='word';row.textContent=`${p.malay||p.ms||p.id} — ${p.chinese||p.zh||''} · Leitner 盒 ${state.vocab[p.id]||1}`;list.append(row);if(hasMalayVoice())button(row,'🔊',()=>speakMalay(p.malay||p.ms||p.id),true)})};select.addEventListener('change',update);update();button(wrap,'返回',()=>go('title'));return}
if(screen==='exam'){title.textContent='Day 10 畢業小考';if(!currentExam.length){currentExam=exams.filter(e=>e.phase===1).sort(()=>Math.random()-.5).slice(0,10);q=0;score=0}if(q>=10){const passed=score>=7;const p=document.createElement('p');p.textContent=`成績 ${score}/10（${score*10}%）— ${passed?'通過！初期畢業！':'未達 70%，再接再厲。'}`;wrap.append(p);button(wrap,'重新考試',()=>{currentExam=[];render()});button(wrap,'主選單',()=>go('title'));return}const item=currentExam[q];const prompt=document.createElement('p');prompt.textContent=`第 ${q+1}/10 題：${item.prompt}`;wrap.append(prompt);const answer=fillBlank(wrap);button(wrap,'作答',()=>{if(gradeAnswer(answer.value,item.answer).correct)score++;q++;render()});return}
if(screen==='settings'){title.textContent='設定與存檔';const note=document.createElement('p');note.textContent=hasMalayVoice()?'已找到馬來語朗讀語音（ms-MY 優先，否則 id-ID）。':'此裝置沒有 ms-MY 或 id-ID 語音，朗讀按鈕會隱藏；遊戲仍可正常遊玩。';wrap.append(note);button(wrap,'下載存檔',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportSave(state)],{type:'application/json'}));a.download='kawan-save.json';a.click();URL.revokeObjectURL(a.href)});const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.addEventListener('change',async()=>{const result=importSave(await file.files[0].text());if(result.valid){state=result.state;persist();render()}else alert('存檔格式無效')});wrap.append(file);button(wrap,'返回',()=>go('title'));return}button(wrap,'繼續',()=>go('briefing'))}
window.addEventListener('keydown',e=>{if(['1','2','3','4'].includes(e.key)){const buttons=[...root.querySelectorAll('button')];buttons[Number(e.key)-1]?.click()}});render();
